import type { Metadata } from "next";
import "./globals.css";
import { Josefin_Sans } from "next/font/google"
import Upperfooter from './component/footer'
import Lowerheader from "./component/header";

const josefin_Sans=Josefin_Sans ({
  weight:['300' , '400' ,'700' ],
  subsets:["latin"],
});


export const metadata: Metadata = {
  title: "Hekto",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={josefin_Sans.className}
      ><Lowerheader/>
        <div className="mb-20 mt-20">{children}</div>
        <Upperfooter/>
      </body>
    </html>
  );
}
